services:
  bailly-api:
    container_name: bailly-api-dev
    stdin_open: true
    tty: true
    env_file:
      - .env.development
    environment:
      - DENO_DIR=/deno-dir
      - HOST_DB=${HOST_DB:-}
    volumes:
      - deno-cache:/deno-dir
      - ${HOST_DB:-host-db}:/host-database/host.db:ro
      - host-db-cache:/app/database
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./deno.json
        - action: rebuild
          path: ./deno.lock
volumes:
  deno-cache:
  host-db:
  host-db-cache:
