export enum AdditionalChar {
  ALL = 1,
  DIGAMMA,
  YOT,
  LUNATE_SIGMA,
  STIGMA,
  KOPPA,
  ARCHAIC_KOPPA,
  SAMPI
  //SAN
}

export enum Chars {
  LETTER_ALPHA,
  LETTER_BETA,
  LETTER_GAMMA,
  LETTER_DELTA,
  LETTER_EPSILON,
  LETTER_ZETA,
  LETTER_ETA,
  LETTER_THETA,
  LETTER_IOTA,
  LETTER_KAPPA,
  LETTER_LAMBDA,
  LETTER_MU,
  LETTER_NU,
  LETTER_XI,
  LETTER_OMICRON,
  LETTER_PI,
  LETTER_RHO,
  LETTER_LUNATE_SIGMA,
  LETTER_SIGMA,
  LETTER_TAU,
  LETTER_UPSILON,
  LETTER_PHI,
  LETTER_CHI,
  LETTER_PSI,
  LETTER_OMEGA,
  LETTER_DIGAMMA,
  LETTER_YOT,
  LETTER_STIGMA,
  LETTER_KOPPA,
  LETTER_ARCHAIC_KOPPA,
  LETTER_SAMPI,
  //LETTER_SAN,
  QUESTION_MARK,
  ANO_TELEIA
}

export enum Coronis {
  PSILI = 'SMOOTH_BREATHING',
  APOSTROPHE = 'RIGHT_SINGLE_QUOTATION_MARK',
  NO = ''
}

export enum KeyType {
  GREEK = 'gr',
  BETA_CODE = 'bc',
  SIMPLE_BETA_CODE = 'sbc',
  TRANSLITERATION = 'tr'
}

export enum Preset {
  ALA_LC,
  ALA_LC_MODERN,
  BNF_ADAPTED,
  ISO,
  SBL,
  TLG
}
